output_path: /home/rnavarro/test_rosbags
buffer_size: 2048
chunk_size: 768
topics: [/vulcano/robotnik_base_hw/battery/alarm,
/vulcano/robotnik_base_hw/battery/data,
/vulcano/robotnik_base_hw/battery/docking_status,
/vulcano/robotnik_base_hw/battery/voltage,
/vulcano/robotnik_base_hw/emergency_stop,
/vulcano/robotnik_base_hw/io,
/vulcano/robotnik_base_hw/state,
/vulcano/robotnik_base_hw/status,
]
split: true
split_size: 1024
compressed: true
