output_folder: /home/ndiaz/test_rosbags
buffer_size: 2048
chunk_size: 768
topics:
 - /robot/front_laser/scan
 - /robot/move_base/local_costmap/obstacle_laser_layer/parameter_descriptions
 - /robot/move_base/local_costmap/obstacle_laser_layer/parameter_updates
 - /robot/rear_laser/scan
split: true
split_size: 1024
compressed: true
regex: true
