<?xml version="1.0"?>
<?xml-model
   href="http://download.ros.org/schema/package_format3.xsd"
   schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>robotnik_advanced_system_monitor</name>
  <version>1.1.1</version>
  <description>The robotnik_advanced_system_monitor package</description>

  <maintainer email="jnavarrete@robotnik.es">Juan Manuel Navarrete</maintainer>
  <license>BSD-3-Clause</license>

  <url type="website">https://github.com/RobotnikAutomation/robotnik_utils</url>
  <url type="repository">https://github.com/RobotnikAutomation/robotnik_utils.git</url>
  <url type="bugtracker">https://github.com/RobotnikAutomation/robotnik_utils/issues</url>

  <author email="jnavarrete@robotnik.es">Juan Manuel Navarrete</author>

  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>roscpp</build_depend>
  <build_depend>rospy</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_export_depend>roscpp</build_export_depend>
  <build_export_depend>rospy</build_export_depend>
  <build_export_depend>std_msgs</build_export_depend>
  <exec_depend>roscpp</exec_depend>
  <exec_depend>rospy</exec_depend>
  <exec_depend>std_msgs</exec_depend>

  <export>
  </export>
</package>
